### PR TITLE
Upgrade ws to latest (1.1.1).

### PR DESCRIPTION
**Pull request by devel-pa**
Nothing more.

### CODE REVIEW

**Comment by mafintosh** [comment]
this `^` already upgrades it to 1.1.1 or am i missing something?

**Comment by devel-pa** [comment]
I agree with you, it should, but no success in my stuff. If you think is useless I'll remove the pull request.

**Comment by mcollina** [comment]
Have you `rm -rf node_modules` in your project folder?

**Comment by devel-pa** [comment]
Yeap, deleted. Looks like something happens on one of the projects that force the stack to go ws 1.0.1. My pull request is useless. Sorry for the noise.

**Pull request closed without merging**
