### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by seriousme** [comment]
@mcollina  can someone please review and merge?
E.g. the current 'ws' version 3.2.0 is 4 major versions behind and has a security vulnerability :-(

TIA,
Hans

**Comment by orgads** [comment]
Updated to latest everything, including duplexify.

**Comment by mcollina** [comment]
Why do you think this module is worth maintaining? `ws` has direct support for Node streams now.

**Comment by orgads** [comment]
Oh, nice! I wasn't aware of it.

Thanks.

**Comment by seriousme** [comment]
If its not worth maintaining wouldn't it be more clear to (potential) users to mark it as `deprecated` on the home page and on NPM  and point to `ws` instead ? That would stop people asking for updates and would warn people that still depend on it and don't know it is no longer maintained anymore. Having unmarked orphaned code imho weakens the security of the node ecosystem.

**Pull request closed without merging**
