### PR TITLE
Cork logic fix for browsers

### PR DESCRIPTION
**Pull request by scarry1992**

### CODE REVIEW

**Comment by mcollina** [comment]
I don't understand this change. It should also re-apply those changes I reverted.

Also, do you know how it fixes #148?

**Comment by scarry1992** [comment]
@mcollina, I have no idea what breaks him logic. I don`t change default logic. You can see it in code.

**Comment by scarry1992** [comment]
@mcollina, need more info from @binarykitchen.

**Comment by scarry1992** [comment]
@mcollina, so, what we are doing?

**Comment by mcollina** [comment]
We wait for @binarykitchen - I had some doubt on that change from the beginning however I couldn't pinpoint the issue. Seems that change is breaking.

(This PR is not complete - it should re-revert my change).

**Comment by scarry1992** [comment]
if try simple test with @binarykitchen settings - it passed

```js
test('echo works', function(t) {
  var stream = ws('ws://localhost:8343', {objectMode: true, perMessageDeflate: false})
  stream.on('data', function(o) {
    t.ok(Buffer.isBuffer(o), 'is buffer')
    t.equal(o.toString(), 'hello', 'got hello back')
    stream.destroy()
    t.end()
  })
  stream.write(Buffer.from('hello'))
})
```

**Comment by scarry1992** [comment]
I fixed situation @binarykitchen. But I confused, because in this case I get separate one packet on two socket frames anytime.
First frame of packet:
photo_2019-04-03_19-02-54
Second frame of packet:
photo_2019-04-03_19-02-56
Maybe @mcollina you know what`s going on?

**Pull request merged**
