### PR TITLE
Add options argument to constructor

### PR DESCRIPTION
**Pull request by binarykitchen**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please add some more tests for the `protocols` options? 

I needed to do this for node:
https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js#L11-L13
and this for the browser:
https://github.com/mqttjs/MQTT.js/blob/master/lib/connect/ws.js#L55

**Comment by binarykitchen** [comment]
Ok, maybe few days later. At the moment I am just confused, see this thread https://github.com/websockets/ws/issues/467

**Comment by mcollina** [comment]
Is it all clear now? I see the other issue is closed.

**Comment by binarykitchen** [comment]
Yes, all clear now. I should have mentioned that I am after the client on the browser side instead. Query string parameters was the answer for me.

**Pull request closed without merging**
