### PR TITLE
Bump ws dev

### PR DESCRIPTION
**Pull request by deanlandolt**
Necessary to fix https://github.com/websockets/ws/pull/632

### CODE REVIEW

**Comment by maxogden** [comment]
thank you!

**Comment by maxogden** [comment]
published 3.0.0 to npm

**Comment by deanlandolt** [comment]
Thanks!

**Comment by deanlandolt** [comment]
I just learned `ws` ripped out browser compatibility in 1.0 -- I'm working up another PR now to add a fallback for browserify support.

**Comment by maxogden** [comment]
Oh interesting! Good catch

**Pull request merged**
