### PR TITLE
Add typings, closes #144

### LINKED ISSUE #144: Add TypeScript definitions?
Could be done here in an `index.d.ts` file (doesn't require installing another package) or in https://github.com/DefinitelyTyped/DefinitelyTyped

### PR DESCRIPTION
**Pull request by benjamincburns**
Title says it all.

I've tested these typings for a few days over at [trufflesuite/ts-lxd](https://github.com/trufflesuite/ts-lxd) and they seem to work great.

### CODE REVIEW

**Comment by mcollina** [comment]
Can you add some verification of the types? ideally compiling a file would  be enough.

**Comment by benjamincburns** [comment]
@mcollina sorry that I didin't see this until now. sure thing!

**Comment by benjamincburns** [comment]
Hopefully that'll do it - can set up a sample TS project if you like but this seemed nicely self-contained and didn't require me to extend/modify the way you're currently handling test execution.

**Comment by mcollina** [comment]
That’s ok. Having a simple file we can compile and check there are no regressions is ok.

**Comment by benjamincburns** [comment]
@mcollina did you need anything else from me before this can be merged?

**Comment by mcollina** [comment]
Nothing really, thank you!

**Pull request merged**
