### PR TITLE
Update 'ws' and wrap ws.Server to avoid future version clash

### PR DESCRIPTION
**Pull request by mcollina**
There is possibly compatibility issue with future versions of `ws`, as for server usage we are currently recommending to use `ws` directly. To fix this I exposed a `websocketStream.Server` here, that inherits from our version of `ws` and also emits a `'stream'` event, in which the connection is already wrapped.

@maxogden @mafintosh please review :).

### CODE REVIEW

**Comment by mafintosh** [comment]
I think this is a good idea. Would like a `var server = websocketStream.createServer(onstream)` function as well as it seems to be the more idiomatic way of doing stuff in node.

**Comment by mcollina** [comment]
Done, but the actual signature is `createServer(opts, onstream)`. Unfortunately [`WebSocketServer`](https://github.com/einaros/ws/blob/master/lib/WebSocketServer.js) supports the 'server' and 'port' thing only in the constructor. I think inheriting here is worth doing, as we do not want to maintain too much this little utility.

**Comment by mafintosh** [comment]
Sweet. Any objections @maxogden ?

**Comment by maxogden** [comment]
lgtm

**Comment by mafintosh** [comment]
Awesome. Released in 1.3.0

**Pull request merged**
