### PR TITLE
Binary with tests

### PR DESCRIPTION
**Pull request by mcollina**
Extremely similar to #94, but improved to avoid that bad-looking option generation.

It also includes tests, and the README update.

cc @mafintosh @laszbalo @Introvertuous - please test before I release as minor.

### CODE REVIEW

**Comment by mcollina** [comment]
I am wondering if we should default `binary` to true, and always convert strings to `Buffer`.

**Comment by Introvertuous** [comment]
I originally assumed that the default was binary and was not sure what was wrong until I stumbled upon the aedes issue (#61).

**Comment by mcollina** [comment]
@Introvertuous I have made the default.

@mafintosh I propose to release this as a minor release. There is a _change_ of functionality, but I argue that was a bug.

**Comment by mcollina** [comment]
merging and releasing.

**Pull request merged**
